vich_uploader:
    db_driver: orm

    mappings:
        archivos:
            uri_prefix: /archivos/comprobantes
            upload_destination: '%kernel.project_dir%/public/archivos/comprobantes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
