# index:
#    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /index.php/login
    permanent: true
# index:
#   path: /login
#   controller: App\Controller\LoginController::login
#   schemes: [https]
